# Generated by Django 2.1.7 on 2019-03-16 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officematter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'Clients',
            },
        ),
    ]
