# Generated by Django 2.1.7 on 2019-03-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officematter', '0002_clientsinformation_user_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsinformation',
            name='user',
        ),
        migrations.AddField(
            model_name='clientsinformation',
            name='bio',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
