# Generated by Django 2.1.7 on 2019-03-26 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officematter', '0004_auto_20190327_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'Type',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='IsPublic',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='Purpose',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='Name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='officematter.Type'),
        ),
    ]
