# Generated by Django 2.1.7 on 2019-03-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officematter', '0005_auto_20190327_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='Image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
