# Generated by Django 2.1.7 on 2019-03-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officematter', '0006_organization_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='Image',
            field=models.ImageField(blank=True, default='images/favicon.ico', null=True, upload_to='images/'),
        ),
    ]
