# Generated by Django 2.1.7 on 2019-03-31 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officematter', '0007_auto_20190330_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Code', models.CharField(max_length=200, unique=True)),
                ('NumberStaff', models.IntegerField()),
                ('Budget', models.IntegerField()),
                ('Revenue', models.IntegerField()),
                ('Address', models.CharField(max_length=200)),
                ('OrgId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='officematter.Organization')),
            ],
            options={
                'db_table': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Code', models.CharField(max_length=200, unique=True)),
                ('NumberDoctor', models.IntegerField()),
                ('NumberNurser', models.IntegerField()),
                ('NumberStaff', models.IntegerField()),
                ('NumberPatientInMonth', models.IntegerField()),
                ('Address', models.CharField(max_length=200)),
                ('OrgId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='officematter.Organization')),
            ],
            options={
                'db_table': 'Hospital',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Code', models.CharField(max_length=200, unique=True)),
                ('NumberTeacher', models.IntegerField()),
                ('NumberStudent', models.IntegerField()),
                ('NumberClass', models.IntegerField()),
                ('Address', models.CharField(max_length=200)),
                ('OrgId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='officematter.Organization')),
            ],
            options={
                'db_table': 'School',
            },
        ),
    ]
